default: pack-problem

mkdir-dist:
    mkdir -p ./dist

build-judger: mkdir-dist
    CGO_ENABLED=0 go build -o ./dist/judge ./judge

pack-problem: mkdir-dist build-judger
    tar cf ./dist/packed.tar problem.json judge.sh
    cd dist && tar rf packed.tar judge && cd ..
    cd data && tar rf ../dist/packed.tar * && cd ..
    mv ./dist/packed.tar ../dist/$(basename $(pwd)).tar
    rm dist -r

clean: mkdir-dist
    rm dist -r
    rm ../dist/$(basename $(pwd)).tar
