default: pack-problem

mkdir-dist:
    mkdir -p ./dist

pack-problem: mkdir-dist
    tar cf ./dist/packed.tar problem.json
    mv ./dist/packed.tar ../dist/$(basename $(pwd)).tar
    rm dist -r

clean: mkdir-dist
    rm dist -r
    rm ../dist/$(basename $(pwd)).tar
